# CURRENT_DATE 当前日期
SELECT CURRENT_DATE() FROM DUAL;
# CURRENT_TIME 当前时间
SELECT CURRENT_TIME() FROM DUAL;
# CURRENT_TIMESTAMP 当前时间戳
## CURRENT_TIMESTAMP , CURRENT_TIME , NOW()  三者完全等价
SELECT CURRENT_TIMESTAMP() FROM DUAL;
# DATE(datetime) 返回dtaetime的日期部分
SELECT DATE() FROM DUAL;
SELECT DATE(CURRENT_TIMESTAMP()) FROM DUAL;

# DATE_ADD(date2,INTERVAL d_valued_type) 在date2上加上日期或时间
# DATE_SUB(date2,INTERVAL d_valued_type) 在date2上减去日期或时间
SELECT DATE_ADD(NOW(),INTERVAL 10 MINUTE) FROM DUAL;
SELECT DATE_ADD(NOW(),INTERVAL 10 HOUR) FROM DUAL;
SELECT DATE_ADD(NOW(),INTERVAL 10 SECOND) FROM DUAL;
SELECT DATE_ADD(NOW(),INTERVAL 10 YEAR) FROM DUAL;
SELECT DATE_ADD(NOW(),INTERVAL 10 MONTH) FROM DUAL;
SELECT DATE_ADD(NOW(),INTERVAL 10 WEEK) FROM DUAL;

SELECT * FROM mes
	WHERE DATE_ADD(send_time,INTERVAL 10 MINUTE) >= NOW();
SELECT * FROM mes
	WHERE DATE_SUB(CURRENT_TIME,INTERVAL 10 MINUTE) <= send_time;


# DATEDIFF(date1,date2) 两个日期差(结果是天)
SELECT DATEDIFF('2011-11-11','1990-01-01') FROM DUAL;
SELECT DATEDIFF(CURRENT_DATE(),'2007-03-25')/365 AS my_life FROM DUAL;
SELECT DATEDIFF(DATE_ADD('2007-03-25',INTERVAL 80 YEAR),CURRENT_DATE())/365 FROM DUAL;
# TIMEDIFF(date1,date2) 两个日期差(xx小时xx分钟秒)
SELECT TIMEDIFF('15:12:12','13:12:12') FROM DUAL;

# NOW() 返回当前日期+时间
# YEAR|Month|DATE(datetime) 只查看datetime的年|月|日
SELECT YEAR(NOW()) FROM DUAL;
SELECT MONTH(NOW()) FROM DUAL;
SELECT DATE(NOW()) FROM DUAL;

SELECT TIME(NOW()) FROM DUAL;
SELECT HOUR(NOW()) FROM DUAL;
SELECT MINUTE(NOW()) FROM DUAL;
SELECT SECOND(NOW()) FROM DUAL;

# FROM_UNIXTIME() 可以把一个unix_timestamp秒数转换为一个指定格式的日期,用百分号作为占位符
## 在开发中可以存放一个整数表示一个时间,运用此函数转换为日期
SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(),'%Y-%M-%d %H:%I:%s') FROM DUAL;
# unix_timestamp  返回1970-1-1到现在的秒数,即真正的==时间戳==
SELECT UNIX_TIMESTAMP() FROM DUAL;
SELECT UNIX_TIMESTAMP()/(24*3600*365) FROM DUAL;